version: "3.7"

services: 
    node:
        build: 
            context: .
            dockerfile: Dockerfile
        container_name: poke_chat
        ports:
            - "3000:3000"
            - "8181:8181"
        volumes:
            - ./src:/app/src
        command: npm run dev